/**
 * MIT License
 *
 * Copyright (c) 2026 Tellcode1
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include "bfunc.h"
#include "bvar.h"
#include "exec.h"
#include "fn.h"
#include "pool.h"
#include "rwhelp.h"
#include "stack.h"
#include "stdafx.h"
#include "sysexpose.h"
#include "var.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int boog = 3;

static inline FILE*
f_from_var(const e_var* v)
{
  FILE* f = v->val.generic_ptr;
  if ((long)f == EB_IO_STDOUT) {
    f = stdout;
  } else if ((long)f == EB_IO_STDERR) {
    f = stderr;
  } else if ((long)f == EB_IO_STDIN) {
    f = stdin;
  }

  return f;
}

static e_var
gooboog(e_var* args, u32 nargs)
{
  (void)nargs;
  (void)args;
  return (e_var){
    .type  = E_VARTYPE_INT,
    .val.i = boog--,
  };
}

static e_var
say_hello_from_c(e_var* args, u32 nargs)
{
  (void)nargs;
  (void)args;
  printf("And this function was called from C, from the script!!\n");

  return (e_var){ .type = E_VARTYPE_NULL };
}

static inline int
find_func(const char* name, u32 nfuncs, const e_function* funcs, e_function* out)
{
  u32 hash = e_hash_fnv(name, strlen(name));
  for (u32 i = 0; i < nfuncs; i++) {
    if (funcs[i].name_hash == hash) {
      *out = funcs[i];
      return 0;
    }
  }
  return -1;
}

int
main(int argc, char* argv[])
{
  // assert(argc == 2);
  e_argv = argv;
  e_argc = argc;

  const char* entry_point = "main";
  for (int i = 0; i < argc; i++) {
    const char* opt = argv[i];
    if (*opt == '-') opt++;
    if (*opt == '-') opt++;

    if (strcmp(opt, "entry") == 0 && i + 1 < argc) { entry_point = argv[i + 1]; }
  }

  FILE* f = fopen(argv[1], "rb");

  if (!f) {
    perror("eexec: Failed to open file");
    return -1;
  }

  void*       root_allocation = nullptr;
  e_var*      lits            = nullptr;
  u8*         ins             = nullptr;
  e_function* funcs           = nullptr;
  u32         nlits           = 0;
  u32         nins            = 0;
  u32         nfuncs          = 0;

  int e = 0;
  if ((e = e_file_load(f, &root_allocation, &nins, &ins, &nlits, &lits, &nfuncs, &funcs))) {
    fprintf(stderr, "eexec: Failed to parse input file: %i\n", e);
    return -1;
  }

  e_function main_func;
  if (find_func(entry_point, nfuncs, funcs, &main_func)) {
    fprintf(stderr, "eexec: File does not have the entry point specified: '%s'\n", entry_point);
    return -1;
  }

#define include_fn(name) (e_builtin_func){ #name, "Autogenerated external function", "external " #name "()", 0xFFFFFFFF, 0, 0, name }
#define include_fn_as(name, as) (e_builtin_func){ #as, "Autogenerated external function", "external " #as "()", 0xFFFFFFFF, 0, 0, name }

  e_builtin_func externals[] = {
    include_fn(say_hello_from_c),
    include_fn(gooboog),
  };

  e_stack stack;
  if (e_stack_init(256, 8, 32, &stack)) return -1;

  if (e_refdobj_pool_init(8, &ge_pool)) return -1;

  e_exec_info info = {
    .args          = nullptr,
    .slots         = nullptr,
    .literals      = lits,
    .funcs         = funcs,
    .code          = ins,
    .code_size     = nins,
    .nargs         = 0,
    .nliterals     = nlits,
    .nfuncs        = nfuncs,
    .stack         = &stack,
    .nextern_funcs = sizeof(externals) / sizeof(externals[0]),
    .extern_funcs  = externals,
  };

  e_stack_push_frame(&stack);

  /**
   * Global variable initialization
   */
  e_var v = e_exec(&info);

  if (v.type != E_VARTYPE_NULL) {
    fputs("Program initialization returned non-null variable: ", stdout);
    eb_println(&v, 1);
    return -1;
  }

  info.code      = main_func.code;
  info.code_size = main_func.code_size;
  /* Execute main function. */
  v = e_exec(&info);

  fputs("Program returned: ", stdout);
  eb_println(&v, 1);

  e_var_release(&v);

  e_stack_pop_frame(&stack);

  fclose(f);
  e_stack_free(&stack);

  e_refdobj_pool_free(&ge_pool);

  /* No need to free anything else */
  free(root_allocation);

  return e;
}