/**
 * MIT License
 *
 * Copyright (c) 2026 Tellcode1
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include "bfunc.h"
#include "exec.h"
#include "fn.h"
#include "pool.h"
#include "rwhelp.h"
#include "stack.h"
#include "sysexpose.h"
#include "var.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int boog = 3;

static e_var
gooboog(e_var* args, u32 nargs)
{
  (void)nargs;
  (void)args;
  return (e_var){
    .type  = E_VARTYPE_INT,
    .val.i = boog--,
  };
}

static e_var
say_hello_from_c(e_var* args, u32 nargs)
{
  (void)nargs;
  (void)args;
  printf("And this function was called from C, from the script!!\n");

  return (e_var){ .type = E_VARTYPE_NULL };
}

static e_var
file_open(e_var* args, u32 nargs)
{
  (void)nargs;
  e_var file_handle = {
    .type = E_VARTYPE_INT,
  };

  FILE* f = fopen(E_VAR_AS_STRING(&args[0])->s, E_VAR_AS_STRING(&args[1])->s);
  memcpy(&file_handle.val, &f, sizeof(f));

  return file_handle;
}

static e_var
file_close(e_var* args, u32 nargs)
{
  (void)nargs;
  FILE* f;
  memcpy(&f, &args[0].val, sizeof(f));

  fclose(f);

  return (e_var){ .type = E_VARTYPE_NULL };
}

static e_var
file_read(e_var* args, u32 nargs)
{
  (void)nargs;
  FILE* f;
  memcpy(&f, &args[0].val, sizeof(f));

  fseek(f, 0, SEEK_END);
  long size = ftell(f);

  char* str = malloc(size + 1);

  fseek(f, 0, SEEK_SET);
  fread(str, size, 1, f);

  str[size] = 0;

  struct e_refdobj* es = e_refdobj_pool_acquire(&ge_pool);

  E_OBJ_AS_STRING(es)->s = str;

  return (e_var){
    .type  = E_VARTYPE_STRING,
    .val.s = es,
  };
}

static e_var
file_size(e_var* args, u32 nargs)
{
  (void)nargs;
  FILE* f;
  memcpy(&f, &args[0].val, sizeof(f));

  long pos = ftell(f);
  if (pos <= 0) return (e_var){ 0 };

  fseek(f, 0, SEEK_END);
  long size = ftell(f);

  fseek(f, pos, SEEK_SET);

  return (e_var){
    .type  = E_VARTYPE_INT,
    .val.i = (int)size,
  };
}

int
main(int argc, char* argv[])
{
  // assert(argc == 2);
  e_argv = argv;
  e_argc = argc;

  FILE* f = fopen(argv[1], "rb");

  if (!f) {
    perror("eexec: Failed to open file");
    return -1;
  }

  void*       root_allocation = nullptr;
  e_var*      lits            = nullptr;
  u8*         ins             = nullptr;
  e_function* funcs           = nullptr;
  u32         nlits           = 0;
  u32         nins            = 0;
  u32         nfuncs          = 0;

  int e = 0;
  if ((e = e_file_load(f, &root_allocation, &nins, &ins, &nlits, &lits, &nfuncs, &funcs))) {
    fprintf(stderr, "eexec: Failed to parse input file: %i\n", e);
  }

#define include_fn(name) (e_builtin_func){ #name, "Autogenerated external function", "external " #name "()", 0xFFFFFFFF, 0, 0, name }
#define include_fn_as(name, as) (e_builtin_func){ #as, "Autogenerated external function", "external " #as "()", 0xFFFFFFFF, 0, 0, name }

  e_builtin_func externals[] = {
    include_fn(file_open), include_fn(file_close), include_fn(file_read), include_fn(file_size), include_fn(say_hello_from_c), include_fn(gooboog),
  };

  e_stack stack;
  if (e_stack_init(256, 8, 32, &stack)) return -1;

  if (e_refdobj_pool_init(8, &ge_pool)) return -1;

  e_exec_info info = {
    .args          = nullptr,
    .slots         = nullptr,
    .literals      = lits,
    .funcs         = funcs,
    .code          = ins,
    .code_size     = nins,
    .nargs         = 0,
    .nliterals     = nlits,
    .nfuncs        = nfuncs,
    .stack         = &stack,
    .nextern_funcs = sizeof(externals) / sizeof(externals[0]),
    .extern_funcs  = externals,
  };

  e_stack_push_frame(&stack);

  e_var v = e_exec(&info);

  e_stack_pop_frame(&stack);

  fclose(f);
  e_stack_free(&stack);

  e_refdobj_pool_free(&ge_pool);

  /* No need to free anything else */
  free(root_allocation);

  if (v.type == E_VARTYPE_INT) { e = v.val.i; }
  e_var_release(&v);
  return e;
}